#include <objbase.h>

static const std::string TABLE_NAME = "<TABLE_NAME>";
static const std::string STORED_PROCEDURE_NAME = "<STORED_PROCEDURE_NAME>";
static const std::string PRIMARY_KEY_CONST = "PRIMARY KEY";
static const std::string FOREIGN_KEY_CONST = "FOREIGN KEY";

static const std::string Q_TABLE_LIST = 
	"SELECT RDB$RELATIONS.RDB$RELATION_NAME"
	" FROM RDB$RELATIONS"
	" WHERE RDB$RELATIONS.RDB$VIEW_BLR IS NULL"
	" AND(RDB$RELATIONS.RDB$SYSTEM_FLAG IS NULL OR RDB$RELATIONS.RDB$SYSTEM_FLAG = 0)"
	" ORDER BY RDB$RELATIONS.RDB$RELATION_NAME";

static const std::string Q_STORED_PROCEDURE_LIST = 
	"SELECT RDB$PROCEDURES.RDB$PROCEDURE_NAME FROM RDB$PROCEDURES"
	" ORDER BY RDB$PROCEDURES.RDB$PROCEDURE_NAME";

static const std::string Q_VIEWS_LIST =
	"SELECT RDB$RELATION_NAME"
	" FROM RDB$RELATIONS"
	" WHERE RDB$RELATIONS.RDB$VIEW_BLR IS NOT NULL"
	" AND(RDB$RELATIONS.RDB$SYSTEM_FLAG IS NULL OR RDB$RELATIONS.RDB$SYSTEM_FLAG = 0)"
	" ORDER BY RDB$RELATION_NAME";

static const std::string Q_TABLE_FIELD_LIST =
	"SELECT RDB$RELATION_FIELDS.RDB$FIELD_NAME, RDB$FIELDS.RDB$FIELD_TYPE, RDB$FIELDS.RDB$FIELD_LENGTH, RDB$FIELDS.RDB$FIELD_SCALE,"
	" RDB$FIELDS.RDB$FIELD_PRECISION, RDB$FIELDS.RDB$CHARACTER_SET_ID, RDB$CHARACTER_SETS.RDB$CHARACTER_SET_NAME, RDB$RELATION_FIELDS.RDB$NULL_FLAG,"
	" (SELECT RDB$RELATION_CONSTRAINTS.RDB$CONSTRAINT_TYPE"
	" FROM RDB$RELATION_CONSTRAINTS, RDB$INDEX_SEGMENTS"
	" WHERE "
	" RDB$RELATION_CONSTRAINTS.RDB$RELATION_NAME = RDB$RELATION_FIELDS.RDB$RELATION_NAME"
	" AND RDB$RELATION_CONSTRAINTS.RDB$INDEX_NAME = RDB$INDEX_SEGMENTS.RDB$INDEX_NAME"
	" AND RDB$INDEX_SEGMENTS.RDB$FIELD_NAME = RDB$RELATION_FIELDS.RDB$FIELD_NAME) AS CONSTRAINT_TYPE"
	" FROM RDB$RELATION_FIELDS"
	" LEFT JOIN RDB$FIELDS ON RDB$RELATION_FIELDS.RDB$FIELD_SOURCE = RDB$FIELDS.RDB$FIELD_NAME"
	" LEFT JOIN RDB$CHARACTER_SETS RDB$CHARACTER_SETS ON RDB$FIELDS.RDB$CHARACTER_SET_ID = RDB$CHARACTER_SETS.RDB$CHARACTER_SET_ID"
	" WHERE RDB$RELATION_FIELDS.RDB$RELATION_NAME = '" + TABLE_NAME + "'"
	" ORDER BY RDB$RELATION_FIELDS.RDB$FIELD_POSITION";

static const std::string Q_STORED_PROCEDURE_FIELD_LIST = 
	"SELECT RDB$PROCEDURE_PARAMETERS.RDB$PARAMETER_NAME, RDB$FIELDS.RDB$FIELD_TYPE, RDB$FIELDS.RDB$FIELD_LENGTH, RDB$FIELDS.RDB$FIELD_SCALE, RDB$FIELDS.RDB$FIELD_PRECISION,"
	" RDB$FIELDS.RDB$CHARACTER_SET_ID, RDB$CHARACTER_SETS.RDB$CHARACTER_SET_NAME, RDB$PROCEDURE_PARAMETERS.RDB$PARAMETER_TYPE"
	" FROM RDB$PROCEDURE_PARAMETERS, RDB$FIELDS"
	" LEFT JOIN RDB$CHARACTER_SETS RDB$CHARACTER_SETS ON RDB$FIELDS.RDB$CHARACTER_SET_ID = RDB$CHARACTER_SETS.RDB$CHARACTER_SET_ID"
	" WHERE RDB$PROCEDURE_PARAMETERS.RDB$PROCEDURE_NAME = '" + STORED_PROCEDURE_NAME + "'"
	" AND RDB$FIELDS.RDB$FIELD_NAME = RDB$PROCEDURE_PARAMETERS.RDB$FIELD_SOURCE"
	" ORDER BY RDB$PROCEDURE_PARAMETERS.RDB$PARAMETER_TYPE, RDB$PROCEDURE_PARAMETERS.RDB$PARAMETER_NUMBER";
